2020-05-19T01:30:49.269137+00:00 app[web.1]: Client 936c37bf0d0b414bb98bb8e7434a2db1 disconnected!
2020-05-19T01:30:49.270005+00:00 app[web.1]: disconnect handler error
2020-05-19T01:30:49.270007+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:49.270008+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T01:30:49.270008+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T01:30:49.270009+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T01:30:49.270009+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T01:30:49.270009+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T01:30:49.270010+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T01:30:49.270010+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:49.270011+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:49.270011+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:49.270012+00:00 app[web.1]: *args)
2020-05-19T01:30:49.270012+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:49.270013+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:49.270013+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 115, in on_disconnect
2020-05-19T01:30:49.270014+00:00 app[web.1]: assert room in user_info[username]["latest_socketids"]
2020-05-19T01:30:49.270056+00:00 app[web.1]: AssertionError
2020-05-19T01:30:49.283081+00:00 app[web.1]: Client c18ac701f3e54bf8b0454aa494f69465 connected!
2020-05-19T01:30:49.323390+00:00 app[web.1]: Socket c18ac701f3e54bf8b0454aa494f69465 associated with XiPooh wants to join room AF73
2020-05-19T01:30:49.324347+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:49.324444+00:00 app[web.1]: File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
2020-05-19T01:30:49.324491+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 679, in _handle_event_internal
2020-05-19T01:30:49.324492+00:00 app[web.1]: r = server._trigger_event(data[0], namespace, sid, *data[1:])
2020-05-19T01:30:49.324559+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:49.324560+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:49.324604+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:49.324605+00:00 app[web.1]: *args)
2020-05-19T01:30:49.324637+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:49.324638+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:49.324668+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 40, in register_player
2020-05-19T01:30:49.324669+00:00 app[web.1]: user_info[name]["latest_socketids"][room].append(socketid)
2020-05-19T01:30:49.324717+00:00 app[web.1]: KeyError: 'AF73'
2020-05-19T01:30:49.324851+00:00 app[web.1]: 2020-05-19T01:30:49Z <Thread at 0x7feb23a58d48: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7feb23395a20>>(<socketio.server.Server object at 0x7feb23395a20>, 'c18ac701f3e54bf8b0454aa494f69465', ['register_player', {'room': 'AF73', 'name': 'XiPo, '/', None)> failed with KeyError
2020-05-19T01:30:49.324852+00:00 app[web.1]:
2020-05-19T01:30:49.284057+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8gZVq9" host=equations-online.herokuapp.com request_id=358c5cdf-c9a5-458a-800b-5f44e6108a58 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=323 protocol=http
2020-05-19T01:30:51.439516+00:00 heroku[router]: at=info method=GET path="/game/AF73/" host=equations-online.herokuapp.com request_id=c39c9532-1909-425b-ba25-62abaff5fc92 fwd="99.239.144.229" dyno=web.1 connect=1ms service=4ms status=200 bytes=15130 protocol=http
2020-05-19T01:30:51.494221+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8gZWMq" host=equations-online.herokuapp.com request_id=621ae0f8-0ff8-4e47-b834-51b1e2dae106 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=323 protocol=http
2020-05-19T01:30:51.511254+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=equations-online.herokuapp.com request_id=865192b7-e3f4-421d-ba13-f0fd136c075c fwd="99.239.144.229" dyno=web.1 connect=0ms service=4ms status=200 bytes=15687 protocol=http
2020-05-19T01:30:51.481881+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=c18ac701f3e54bf8b0454aa494f69465" host=equations-online.herokuapp.com request_id=c873b436-e1bc-4cee-ab96-5c7c0432f7ee fwd="99.239.144.229" dyno=web.1 connect=1ms service=2114ms status=101 bytes=143 protocol=http
2020-05-19T01:30:51.533545+00:00 heroku[router]: at=info method=POST path="/socket.io/?EIO=3&transport=polling&t=N8gZWNP.0&sid=c2f18cf3141e4b459ae716cb040e0291" host=equations-online.herokuapp.com request_id=2aa3e3ce-814e-4185-8d57-a7bb0d0e5f82 fwd="99.239.144.229" dyno=web.1 connect=0ms service=2ms status=200 bytes=211 protocol=http
2020-05-19T01:30:51.482237+00:00 app[web.1]: Client c18ac701f3e54bf8b0454aa494f69465 disconnected!
2020-05-19T01:30:51.482881+00:00 app[web.1]: disconnect handler error
2020-05-19T01:30:51.482882+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:51.482883+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T01:30:51.482884+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T01:30:51.482884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T01:30:51.482885+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T01:30:51.482885+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T01:30:51.482885+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T01:30:51.482886+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:51.482886+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:51.482887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:51.482888+00:00 app[web.1]: *args)
2020-05-19T01:30:51.482888+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:51.482888+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:51.482889+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 115, in on_disconnect
2020-05-19T01:30:51.482889+00:00 app[web.1]: assert room in user_info[username]["latest_socketids"]
2020-05-19T01:30:51.482937+00:00 app[web.1]: AssertionError
2020-05-19T01:30:51.492715+00:00 app[web.1]: Client c2f18cf3141e4b459ae716cb040e0291 connected!
2020-05-19T01:30:51.536189+00:00 app[web.1]: Socket c2f18cf3141e4b459ae716cb040e0291 associated with XiPooh wants to join room AF73
2020-05-19T01:30:51.537054+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:51.537140+00:00 app[web.1]: File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
2020-05-19T01:30:51.537175+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 679, in _handle_event_internal
2020-05-19T01:30:51.537176+00:00 app[web.1]: r = server._trigger_event(data[0], namespace, sid, *data[1:])
2020-05-19T01:30:51.537210+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:51.537211+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:51.537245+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:51.537246+00:00 app[web.1]: *args)
2020-05-19T01:30:51.537278+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:51.537279+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:51.537312+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 40, in register_player
2020-05-19T01:30:51.537313+00:00 app[web.1]: user_info[name]["latest_socketids"][room].append(socketid)
2020-05-19T01:30:51.537360+00:00 app[web.1]: KeyError: 'AF73'
2020-05-19T01:30:51.537477+00:00 app[web.1]: 2020-05-19T01:30:51Z <Thread at 0x7feb23a58e48: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7feb23395a20>>(<socketio.server.Server object at 0x7feb23395a20>, 'c2f18cf3141e4b459ae716cb040e0291', ['register_player', {'room': 'AF73', 'name': 'XiPo, '/', None)> failed with KeyError
2020-05-19T01:30:51.537477+00:00 app[web.1]:
2020-05-19T01:30:51.633672+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8gZWNP&sid=c2f18cf3141e4b459ae716cb040e0291" host=equations-online.herokuapp.com request_id=1a97e5ed-a800-4f0f-a9ce-59867fdeee26 fwd="99.239.144.229" dyno=web.1 connect=0ms service=102ms status=200 bytes=159 protocol=http
2020-05-19T01:30:55.394548+00:00 heroku[router]: at=info method=GET path="/" host=equations-online.herokuapp.com request_id=8bd35295-3f21-4b77-890e-a42e09b180c2 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=3069 protocol=https
2020-05-19T01:30:55.437727+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=c2f18cf3141e4b459ae716cb040e0291" host=equations-online.herokuapp.com request_id=8bf212ba-a260-4b29-aeda-add8e3a59e27 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3844ms status=101 bytes=146 protocol=http
2020-05-19T01:30:55.437099+00:00 app[web.1]: Client c2f18cf3141e4b459ae716cb040e0291 disconnected!
2020-05-19T01:30:55.437723+00:00 app[web.1]: disconnect handler error
2020-05-19T01:30:55.437725+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:55.437725+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T01:30:55.437726+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T01:30:55.437727+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T01:30:55.437727+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T01:30:55.437727+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T01:30:55.437728+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T01:30:55.437728+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:55.437729+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:55.437729+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:55.437730+00:00 app[web.1]: *args)
2020-05-19T01:30:55.437730+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:55.437730+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:55.437731+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 115, in on_disconnect
2020-05-19T01:30:55.437731+00:00 app[web.1]: assert room in user_info[username]["latest_socketids"]
2020-05-19T01:30:55.437767+00:00 app[web.1]: AssertionError
